#!/bin/bash
# ==================================================================================================
# Bash Fragments
# ==================================================================================================

function hello() {
    echo "Hello world!"
}

function hello2() { echo "Hello"; echo "world2!"; }

hello
hello2

if [ -d . ]; then
    echo "Whereever you go, there you are."
elif [ -f . ]; then
    echo "Or somewhere else."
else
    echo "Or nowhere."
fi

for word in Hello solar system!; {
    echo "> " $word
}

if [[ "xyz" != "xyz" ]]; then echo "Something's wrong!"; fi

if which -s git; then echo Git is installed.; fi
if ! which -s git; then echo Git is not installed.; fi

some-command | while read -a line
do
    echo "Entire line: ${line[@]}"
    echo "Token 0: ${line[0]}"
    echo "Token 1: ${line[1]}"
    echo "Token 2: ${line[2]}"
done
